//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSolutionRation.wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VetSolutionRatioRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VetSolutionRatioRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetSolutionRation.wpf.Properties.VetSolutionRatioRes", typeof(VetSolutionRatioRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cow.
        /// </summary>
        internal static string AnimalKind_BovineFemale {
            get {
                return ResourceManager.GetString("AnimalKind_BovineFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bull.
        /// </summary>
        internal static string AnimalKind_BovineMale {
            get {
                return ResourceManager.GetString("AnimalKind_BovineMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She-goat.
        /// </summary>
        internal static string AnimalKind_GoatFemale {
            get {
                return ResourceManager.GetString("AnimalKind_GoatFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He-goat.
        /// </summary>
        internal static string AnimalKind_GoatMale {
            get {
                return ResourceManager.GetString("AnimalKind_GoatMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mare.
        /// </summary>
        internal static string AnimalKind_HorseFemale {
            get {
                return ResourceManager.GetString("AnimalKind_HorseFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string AnimalKind_HorseMale {
            get {
                return ResourceManager.GetString("AnimalKind_HorseMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ewe.
        /// </summary>
        internal static string AnimalKind_SheepFemale {
            get {
                return ResourceManager.GetString("AnimalKind_SheepFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram.
        /// </summary>
        internal static string AnimalKind_SheepMale {
            get {
                return ResourceManager.GetString("AnimalKind_SheepMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heifer.
        /// </summary>
        internal static string AnimalSubKind_Heifer {
            get {
                return ResourceManager.GetString("AnimalSubKind_Heifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate rations.
        /// </summary>
        internal static string FeedSelectionModeCalculateRatiosTitle {
            get {
                return ResourceManager.GetString("FeedSelectionModeCalculateRatiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify rations.
        /// </summary>
        internal static string FeedSelectionModeVerifyRatiosTitle {
            get {
                return ResourceManager.GetString("FeedSelectionModeVerifyRatiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search an animal by nam (splited by space).
        /// </summary>
        internal static string View_AnimalSelection_Search_Hint {
            get {
                return ResourceManager.GetString("View_AnimalSelection_Search_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each part of your search separated by a space will be processed. ie: if you type &quot;gen 1&quot; you will see what contains BOTH &quot;gen&quot; AND &quot;1&quot;, but NOT what would contain only &quot;gen&quot;. Search is not case sensitive .
        /// </summary>
        internal static string View_AnimalSelection_Search_Tooltip {
            get {
                return ResourceManager.GetString("View_AnimalSelection_Search_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to selected feed.
        /// </summary>
        internal static string View_FeedSelection_Verify_AddToSelectionButton_ToolTip {
            get {
                return ResourceManager.GetString("View_FeedSelection_Verify_AddToSelectionButton_ToolTip", resourceCulture);
            }
        }
    }
}
